language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

before_install:
  - pip install --quiet codecov flake8

install:
  - make install

script:
  - make lint

after_success:
  - bash <(curl -s https://codecov.io/bash)
